version: '3.8'

services:
  app:
    image: weather-app-app
    container_name: weather-app-app
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    depends_on:
      - redis
    environment:
      QUEUE_CONNECTION: redis
      DB_CONNECTION: mysql
      DB_HOST: lim.h.filess.io
      DB_PORT: 3307
      DB_DATABASE: weatherforecast_southsmile
      DB_USERNAME: weatherforecast_southsmile
      DB_PASSWORD: db00118637c7ffbc15f8e2003b3eca411b966558
      REDIS_HOST: redis
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: weather-app-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: weather-app-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  queue-worker:
    image: weather-app-app
    container_name: weather-app-queue-worker
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - .:/var/www/html
    depends_on:
      - app
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
